### ISSUE TITLE
Daemon does not communicate with client

### ISSUE THREAD

**Issue by arshesney** [marazmista/radeon-profile-daemon#6]
I can't pinpoint when it actually started having this issue, but I noticed the same problem discussed in the last messages in Phoronix thread: the client returns the "you need debugfs, root privileges or the daemon running" message, yet the socket is present in /tmp.

My system is Arch 4.11.5-2-ck-piledriver x86_64, using amdgpu with an R9 390
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390] (rev 80)`

I built both client and daemon with debug enabled, this is daemon's output:
```
% sudo env QT_LOGGING_RULES=\*.debug=true ./radeon-profile-daemon                                                                          :(
Starting in debug mode
ok
Connecting to the client
Performing task:  "0#/sys/kernel/debug/dri/0/amdgpu_pm_info#4#1#"
Elaborating a CONFIG signal
The new clocks data path is  "/sys/kernel/debug/dri/0/amdgpu_pm_info"
"/sys/kernel/debug/dri/0/amdgpu_pm_info"  will be copied into  "/tmp/amdgpu_pm_info"
Elaborating a TIMER_ON signal
Setting up timer with seconds interval:  1
Shared memory is not attached, can't write data:  "QSharedMemory::handle:: key is empty"
Performing task:  "2#1#/sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable#2#142#/sys/class/drm/card0/device/hwmon/hwmon0/pwm1#"
Elaborating a SET_VALUE signal
"1"  will be written into  "/sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable"
Elaborating a SET_VALUE signal
"142"  will be written into  "/sys/class/drm/card0/device/hwmon/hwmon0/pwm1"
Shared memory is not attached, can't write data:  "QSharedMemory::handle:: key is empty"
Performing task:  "2#147#/sys/class/drm/card0/device/hwmon/hwmon0/pwm1#"
Elaborating a SET_VALUE signal
"147"  will be written into  "/sys/class/drm/card0/device/hwmon/hwmon0/pwm1"
Shared memory is not attached, can't write data:  "QSharedMemory::handle:: key is empty"
Performing task:  "2#145#/sys/class/drm/card0/device/hwmon/hwmon0/pwm1#"
Elaborating a SET_VALUE signal
"145"  will be written into  "/sys/class/drm/card0/device/hwmon/hwmon0/pwm1"
Shared memory is not attached, can't write data:  "QSharedMemory::handle:: key is empty"
Performing task:  "2#142#/sys/class/drm/card0/device/hwmon/hwmon0/pwm1#"
Elaborating a SET_VALUE signal
"142"  will be written into  "/sys/class/drm/card0/device/hwmon/hwmon0/pwm1"
Shared memory is not attached, can't write data:  "QSharedMemory::handle:: key is empty"
```
last line is repeated every second.

The client debug log is much more verbose, I attached it to the post.
[debug-client.txt](https://github.com/marazmista/radeon-profile-daemon/files/1086464/debug-client.txt)

The client started with root privileges works as expected.

**Comment by marazmista** [comment]
Thanks for report. Can you try latest daemon with client compiled from `rp-dev` branch? https://github.com/marazmista/radeon-profile/tree/rp-dev

**Comment by arshesney** [comment]
Awesome, rp-dev branch with latest daemon works! The error doesn't appear anymore.
Thank you, having a custom (aggressive) fan profile is the only way to avoid my 390 locking the system up after some uptime.

**Comment by marazmista** [comment]
Fixed with merge `rp-dev`: https://github.com/marazmista/radeon-profile/commit/ac594203b2b89001304d73c38bb3c87a4adbd4c8
