### ISSUE TITLE
Fan profiles with daemon only

### ISSUE THREAD

**Issue by diwic** [marazmista/radeon-profile-daemon#7]
Hi and thanks for making this utility! I want to use my custom fan profile, write it once and never think about it again, just have radeon-profile-daemon running in the background.

However, it seems as, as soon as I quit the radeon-profile GUI the fan goes back to a fixed value (just like when the daemon is not running).

Am I making some stupid newbie mistake (forgot to check the right box), or is this not possible?

**Comment by marazmista** [comment]
Not possible.
Besides, fan doesn't go back to fixed value but to its internal fan control profile. You can probably dump card's BIOS, edit that profile in some special software and flash it again.

**Comment by diwic** [comment]
Cool, thanks for the answer. I'll write my own little script then.
